#!/bin/sh
set -e

case "$1" in
    install)
        addgroup --system signald
        adduser --system --home /var/lib/signald signald
        adduser signald signald  # Add signald user to the signald group
        mkdir -p  /var/lib/signald
        chown -R signald:signald /var/lib/signald
        ;;

    upgrade|abort-upgrade)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
