Document: signald
Title: Debian signald Manual
Author: <insert document author here>
Abstract: This manual describes what signald is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/signald/signald.sgml.gz

Format: postscript
Files: /usr/share/doc/signald/signald.ps.gz

Format: text
Files: /usr/share/doc/signald/signald.text.gz

Format: HTML
Index: /usr/share/doc/signald/html/index.html
Files: /usr/share/doc/signald/html/*.html
